name: test_micromamba

on: [push]

jobs:
  plain_conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        uses: omnibenchmark/run_omnibenchmark@dev
        with:
          yaml: tests/Clustering_conda.yml
          backend: conda
          cores: 1
          conda_handler: micromamba

